### ISSUE TITLE
Add version tag to terraform modules

### ISSUE THREAD

**Issue by chris3ware** [JamesWoolfenden/ghat#10]
**Is your feature request related to a problem? Please describe.**
The example GitHub Action shows the version tag is added at the end of the SHA.

eg:

`22e03ff8b79ce67f4a5059d0d24c3d07d8d69b1b # v4.2.2`

But, when this tool is used with a terraform module, the version tag is not added to the end of the SHA.

eg:

`"git::https://github.com/terraform-aws-modules/terraform-aws-s3-bucket.git?ref=8a0b697adfbc673e6135c70246cff7f8052ad95a"`

**Describe the solution you'd like**
The semantic version tag to be added to the end of the SHA: `#v1.0.0`

**Describe alternatives you've considered**

**Additional context**
I might have a go at solving this myself when I have learnt ~~a bit~~ a lot more golang

**Comment by JamesWoolfenden** [comment]
sorry only just saw this. its fixed in latest release

**Comment by chris3ware** [comment]
Great, thanks.
